import { Router, type IRouter } from "express";
import type { Tool } from "@workspace/api-zod";

const router: IRouter = Router();

const PDF_ACCEPT = ["application/pdf", ".pdf"];
const IMAGE_ACCEPT = ["image/jpeg", "image/png", ".jpg", ".jpeg", ".png"];
const WORD_ACCEPT = [".doc", ".docx"];
const SLIDES_ACCEPT = [".ppt", ".pptx"];
const SHEET_ACCEPT = [".xls", ".xlsx"];
const HTML_ACCEPT = [".html", ".htm", ".zip"];

/**
 * The tool catalog served to the web app.
 *
 * Category, order, names, accent tokens and lucide icons all mirror the
 * reference design (`precision_pdf_utility`) — the six landing sections appear
 * here in the exact order they render: organize, convert-to, convert-from,
 * edit, security, ai.
 *
 * `accent` is a *named token*, never a raw hex: the web app resolves it to
 * `bg-primary/10 text-primary`, `bg-secondary/10 text-secondary`,
 * `bg-tertiary/10 text-tertiary` or `bg-secondary-container/20
 * text-secondary-hover`. Keeping hexes out of the API is deliberate — the
 * palette has exactly one source of truth (`@theme` in `index.css`).
 *
 * `status`/`route` are the authoritative "does a backend route exist" answer.
 * Tools with `status: "pending"` have `route: null` and must render a disabled
 * Process button plus a visible badge rather than calling a missing endpoint.
 */
export const PDF_TOOLS: Tool[] = [
  // ─── Organize PDF ───────────────────────────────────────────────────────────
  {
    id: "merge",
    keywords: ["combine", "join", "concatenate"],
    popular: true,
    name: "Merge PDF",
    description: "Combine multiple PDFs into a single document in seconds.",
    category: "organize",
    accent: "primary",
    icon: "Combine",
    workspace: "stepper",
    status: "implemented",
    route: "/api/pdf/merge",
    inputLabel: "Select PDFs to merge",
    outputLabel: "Merged PDF",
    acceptMultiple: true,
    accept: PDF_ACCEPT,
  },
  {
    id: "compress",
    keywords: ["shrink", "reduce", "optimize", "filesize"],
    name: "Compress PDF",
    description: "Reduce file size while keeping the best possible quality.",
    category: "organize",
    accent: "primary",
    icon: "Minimize2",
    workspace: "stepper",
    status: "implemented",
    route: "/api/pdf/compress",
    inputLabel: "Select PDF to compress",
    outputLabel: "Compressed PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
  {
    id: "split",
    keywords: ["separate", "divide", "break", "extract"],
    name: "Split PDF",
    description: "Separate one page or a whole set into independent PDFs.",
    category: "organize",
    accent: "primary",
    icon: "Scissors",
    workspace: "stepper",
    status: "implemented",
    route: "/api/pdf/split",
    inputLabel: "Select PDF to split",
    outputLabel: "Split pages",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
  {
    id: "remove-pages",
    keywords: ["delete", "strip", "trim", "drop"],
    name: "Remove Pages",
    description: "Delete the pages you don't need and keep the rest of the document intact.",
    category: "organize",
    accent: "primary",
    icon: "FileMinus",
    workspace: "page-picker",
    status: "implemented",
    route: "/api/pdf/remove-pages",
    inputLabel: "Select PDF to remove pages from",
    outputLabel: "Trimmed PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
  {
    id: "extract-pages",
    keywords: ["pull", "isolate", "selective", "slice"],
    name: "Extract Pages",
    description: "Pull the pages you pick into a new document of their own.",
    category: "organize",
    accent: "primary",
    icon: "FileOutput",
    workspace: "page-picker",
    status: "implemented",
    route: "/api/pdf/split",
    inputLabel: "Select PDF to extract pages from",
    outputLabel: "Extracted pages",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
  {
    id: "reorder-pages",
    keywords: ["reorder", "rearrange", "sort", "visual"],
    name: "Organize Pages",
    description: "Drag pages into the order you want, drop the ones you don't, and rebuild the PDF.",
    category: "organize",
    accent: "primary",
    icon: "ListOrdered",
    workspace: "page-picker",
    status: "implemented",
    route: "/api/pdf/reorder-pages",
    inputLabel: "Select PDF to reorganize",
    outputLabel: "Reordered PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
  {
    id: "rotate",
    keywords: ["turn", "orientation", "landscape", "portrait"],
    name: "Rotate PDF",
    description: "Rotate your PDFs the way you need them, one or all pages.",
    category: "organize",
    accent: "primary",
    icon: "RotateCw",
    workspace: "page-picker",
    status: "implemented",
    route: "/api/pdf/rotate",
    inputLabel: "Select PDFs to rotate",
    outputLabel: "Rotated PDF",
    acceptMultiple: true,
    accept: PDF_ACCEPT,
  },

  // ─── Convert to PDF ─────────────────────────────────────────────────────────
  {
    id: "word-to-pdf",
    keywords: ["docx", "doc", "microsoft", "word to pdf"],
    name: "Word to PDF",
    description: "Make DOC and DOCX files easy to read by converting them to PDF.",
    category: "convert-to",
    accent: "secondary",
    icon: "FileText",
    workspace: "stepper",
    status: "pending",
    route: null,
    inputLabel: "Select Word document to convert",
    outputLabel: "PDF document",
    acceptMultiple: false,
    accept: WORD_ACCEPT,
  },
  {
    id: "ppt-to-pdf",
    keywords: ["pptx", "ppt", "presentation", "slides"],
    name: "PowerPoint to PDF",
    description: "Turn slide decks into PDFs that look the same on every device.",
    category: "convert-to",
    accent: "secondary",
    icon: "Presentation",
    workspace: "stepper",
    status: "pending",
    route: null,
    inputLabel: "Select presentation to convert",
    outputLabel: "PDF document",
    acceptMultiple: false,
    accept: SLIDES_ACCEPT,
  },
  {
    id: "excel-to-pdf",
    keywords: ["xlsx", "xls", "spreadsheets", "sheets", "tables"],
    name: "Excel to PDF",
    description: "Convert spreadsheets to PDF while keeping their page layout.",
    category: "convert-to",
    accent: "secondary",
    icon: "Sheet",
    workspace: "stepper",
    status: "pending",
    route: null,
    inputLabel: "Select spreadsheet to convert",
    outputLabel: "PDF document",
    acceptMultiple: false,
    accept: SHEET_ACCEPT,
  },
  {
    id: "images-to-pdf",
    keywords: ["images", "jpeg", "jpg", "png", "photos", "pictures", "to pdf"],
    name: "JPG/PNG to PDF",
    description: "Combine JPG and PNG photos into a single PDF, one image per page.",
    category: "convert-to",
    accent: "secondary",
    icon: "Image",
    workspace: "stepper",
    status: "implemented",
    route: "/api/pdf/images-to-pdf",
    inputLabel: "Select images to convert",
    outputLabel: "PDF from images",
    acceptMultiple: true,
    accept: IMAGE_ACCEPT,
  },
  {
    id: "scan-to-pdf",
    keywords: ["scanner", "camera", "optical", "capture", "receipts"],
    name: "Scan to PDF",
    description: "Capture pages with your camera and turn them into a clean, searchable PDF.",
    category: "convert-to",
    accent: "secondary",
    icon: "ScanText",
    workspace: "stepper",
    status: "pending",
    route: null,
    inputLabel: "Capture or select pages to scan",
    outputLabel: "Scanned PDF",
    acceptMultiple: true,
    accept: IMAGE_ACCEPT,
  },
  {
    id: "html-to-pdf",
    keywords: ["web", "url", "webpage", "browser", "code", "to pdf"],
    name: "HTML to PDF",
    description: "Save a web page as a PDF you can archive, print, or share.",
    category: "convert-to",
    accent: "secondary",
    icon: "Code",
    workspace: "stepper",
    status: "pending",
    route: null,
    inputLabel: "Select HTML file or archive to convert",
    outputLabel: "PDF document",
    acceptMultiple: false,
    accept: HTML_ACCEPT,
  },

  // ─── Convert from PDF ───────────────────────────────────────────────────────
  {
    id: "pdf-to-word",
    keywords: ["doc", "docx", "editable", "word", "convert from pdf"],
    popular: true,
    name: "PDF to Word",
    description: "Turn a PDF into an editable DOCX document you can keep working in.",
    category: "convert-from",
    accent: "secondary",
    icon: "FileText",
    workspace: "stepper",
    status: "pending",
    route: null,
    inputLabel: "Select PDF to convert to Word",
    outputLabel: "Word document",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
  {
    id: "pdf-to-powerpoint",
    keywords: ["slides", "ppt", "pptx", "presentation", "convert"],
    name: "PDF to PowerPoint",
    description: "Turn your PDF pages into an editable slide deck.",
    category: "convert-from",
    accent: "secondary",
    icon: "Presentation",
    workspace: "stepper",
    status: "pending",
    route: null,
    inputLabel: "Select PDF to convert to slides",
    outputLabel: "PowerPoint deck",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
  {
    id: "pdf-to-excel",
    keywords: ["tables", "spreadsheets", "xlsx", "data", "extract"],
    name: "PDF to Excel",
    description: "Pull tables out of a PDF into a spreadsheet you can calculate with.",
    category: "convert-from",
    accent: "secondary",
    icon: "Sheet",
    workspace: "stepper",
    status: "pending",
    route: null,
    inputLabel: "Select PDF to convert to a spreadsheet",
    outputLabel: "Spreadsheet",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
  {
    id: "pdf-to-images",
    keywords: ["pictures", "png", "jpeg", "images", "export"],
    name: "PDF to JPG",
    description: "Turn each PDF page into a JPG or PNG image. Multi-page PDFs are returned as a ZIP.",
    category: "convert-from",
    accent: "secondary",
    icon: "Images",
    workspace: "stepper",
    status: "implemented",
    route: "/api/pdf/pdf-to-images",
    inputLabel: "Select PDF to convert to images",
    outputLabel: "Page images",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
  {
    id: "pdf-to-markdown",
    keywords: ["md", "text", "raw", "documentation", "llm", "formatting"],
    name: "PDF to Markdown",
    description: "Export a PDF as clean Markdown text, with headings and lists preserved.",
    category: "convert-from",
    accent: "secondary",
    icon: "FileCode",
    workspace: "stepper",
    status: "partial",
    route: "/api/pdf/extract-text",
    inputLabel: "Select PDF to convert to Markdown",
    outputLabel: "Markdown file",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
  {
    id: "pdf-to-pdfa",
    keywords: ["archive", "iso", "long term", "preservation", "legal"],
    name: "PDF to PDF/A",
    description: "Convert a PDF into the ISO 19005 archival format for long-term storage.",
    category: "convert-from",
    accent: "secondary",
    icon: "Archive",
    workspace: "stepper",
    status: "implemented",
    route: "/api/pdf/pdf-to-pdfa",
    inputLabel: "Select PDF to convert to PDF/A",
    outputLabel: "PDF/A document",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },

  // ─── Edit PDF ───────────────────────────────────────────────────────────────
  {
    id: "edit-pdf",
    keywords: ["text", "shapes", "annotations", "drawing", "markup"],
    name: "Edit PDF Content",
    description: "Add text, shapes, and images on top of your PDF and save the result.",
    category: "edit",
    accent: "tertiary",
    icon: "PenLine",
    workspace: "stepper",
    status: "pending",
    route: null,
    inputLabel: "Select PDF to edit",
    outputLabel: "Edited PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
  {
    id: "add-page-numbers",
    keywords: ["pagination", "numbering", "bates", "footer", "header"],
    name: "Add Page Numbers",
    description: "Stamp page numbers on every page. Pick position, style, and starting number.",
    category: "edit",
    accent: "tertiary",
    icon: "Hash",
    workspace: "stepper",
    status: "implemented",
    route: "/api/pdf/add-page-numbers",
    inputLabel: "Select PDF to number",
    outputLabel: "Numbered PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
  {
    id: "watermark",
    keywords: ["stamp", "confidential", "opacity", "copyright", "logo"],
    name: "Add Watermark",
    description: "Stamp text or an image over your PDFs. Choose the position and transparency.",
    category: "edit",
    accent: "tertiary",
    icon: "Stamp",
    workspace: "stepper",
    status: "implemented",
    route: "/api/pdf/watermark",
    inputLabel: "Select PDF to watermark",
    outputLabel: "Watermarked PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
  {
    id: "crop",
    keywords: ["trim", "margins", "border", "whitespace", "bounding box"],
    name: "Crop PDF",
    description: "Trim white space or margins from every page, or only the pages you pick.",
    category: "edit",
    accent: "tertiary",
    icon: "Crop",
    workspace: "page-picker",
    status: "implemented",
    route: "/api/pdf/crop",
    inputLabel: "Select PDF to crop",
    outputLabel: "Cropped PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
  {
    id: "pdf-form-filler",
    keywords: ["acroforms", "interactive", "fields", "inputs", "checkboxes"],
    name: "PDF Form Filler",
    description: "Fill in existing PDF form fields and flatten them so the answers stick.",
    category: "edit",
    accent: "tertiary",
    icon: "ClipboardCheck",
    workspace: "stepper",
    status: "pending",
    route: null,
    inputLabel: "Select fillable PDF form",
    outputLabel: "Filled PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },

  // ─── PDF Security ───────────────────────────────────────────────────────────
  {
    id: "protect",
    keywords: ["password", "encrypt", "256", "aes", "lock", "permissions"],
    name: "Protect PDF",
    description: "Encrypt a PDF with AES-256 password protection and choose what readers may do.",
    category: "security",
    accent: "primary",
    icon: "Lock",
    workspace: "stepper",
    status: "implemented",
    route: "/api/pdf/protect",
    inputLabel: "Select PDF to protect",
    outputLabel: "Protected PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
  {
    id: "unlock",
    keywords: ["decrypt", "remove password", "unprotect", "permissions"],
    name: "Unlock PDF",
    description: "Remove PDF password security, giving you the freedom to use your PDFs as you want.",
    category: "security",
    accent: "primary",
    icon: "Unlock",
    workspace: "stepper",
    status: "implemented",
    route: "/api/pdf/unlock",
    inputLabel: "Select PDF to unlock",
    outputLabel: "Unlocked PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
  {
    id: "sign",
    keywords: ["signature", "esign", "electronic", "contract", "autograph"],
    name: "Sign Document",
    description: "Draw, type, or upload a signature and place it on the pages you choose.",
    category: "security",
    accent: "primary",
    icon: "PenTool",
    workspace: "stepper",
    status: "pending",
    route: null,
    inputLabel: "Select PDF to sign",
    outputLabel: "Signed PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
  {
    id: "redact",
    keywords: ["blackout", "censor", "privacy", "pii", "ssn"],
    name: "Redact Sensitive Data",
    description: "Permanently remove confidential text and images from a document.",
    category: "security",
    accent: "primary",
    icon: "Eraser",
    workspace: "stepper",
    status: "pending",
    route: null,
    inputLabel: "Select PDF to redact",
    outputLabel: "Redacted PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },

  // ─── AI Document Tools ──────────────────────────────────────────────────────
  {
    id: "ai-summarize",
    keywords: ["summary", "brief", "overview", "digest", "insights"],
    name: "AI PDF Summarizer",
    description: "Get an instant AI-generated summary and key points from any PDF. Completely free — no paywall.",
    category: "ai",
    accent: "ai",
    icon: "Sparkles",
    workspace: "stepper",
    status: "implemented",
    route: "/api/pdf/ai-summarize",
    inputLabel: "Select PDF to summarize",
    outputLabel: "Summary",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
  {
    id: "translate-pdf",
    keywords: ["multilingual", "languages", "localization", "foreign"],
    name: "Translate PDF",
    description: "Translate a document into another language while keeping its layout readable.",
    category: "ai",
    accent: "ai",
    icon: "Languages",
    workspace: "stepper",
    status: "pending",
    route: null,
    inputLabel: "Select PDF to translate",
    outputLabel: "Translated document",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
  {
    id: "compare",
    keywords: ["diff", "compare", "changes", "revisions", "legal", "audit"],
    name: "Compare Two PDFs",
    description: "See what changed between two versions of a PDF with a line-by-line text comparison.",
    category: "ai",
    accent: "ai",
    icon: "GitCompare",
    workspace: "stepper",
    status: "implemented",
    route: "/api/pdf/compare",
    inputLabel: "Select two PDFs to compare",
    outputLabel: "Comparison report",
    acceptMultiple: true,
    accept: PDF_ACCEPT,
  },
  {
    id: "chat-with-document",
    keywords: ["rag", "ask", "questions", "query", "ai", "search", "citations"],
    name: "Chat with Document",
    description: "Ask questions about a PDF and get answers grounded in its contents.",
    category: "ai",
    accent: "ai",
    icon: "MessageSquare",
    workspace: "stepper",
    status: "pending",
    route: null,
    inputLabel: "Select PDF to chat with",
    outputLabel: "Answers",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
  },
];

router.get("/tools", async (_req, res): Promise<void> => {
  res.json(PDF_TOOLS);
});

export default router;
