import { Router, type IRouter } from "express";

const router: IRouter = Router();

const PDF_ACCEPT = ["application/pdf", ".pdf"];
const IMAGE_ACCEPT = ["image/jpeg", "image/png", ".jpg", ".jpeg", ".png"];

export const PDF_TOOLS = [
  // Organize
  {
    id: "merge",
    name: "Merge PDF",
    description: "Combine multiple PDFs into a single document in seconds.",
    category: "organize",
    icon: "Combine",
    inputLabel: "Select PDFs to merge",
    outputLabel: "Merged PDF",
    acceptMultiple: true,
    accept: PDF_ACCEPT,
    color: "#4F8EF7",
  },
  {
    id: "split",
    name: "Split PDF",
    description: "Separate one page or a whole set into independent PDFs.",
    category: "organize",
    icon: "Scissors",
    inputLabel: "Select PDF to split",
    outputLabel: "Split pages",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
    color: "#4F8EF7",
  },
  {
    id: "rotate",
    name: "Rotate PDF",
    description: "Rotate your PDFs the way you need them, one or all pages.",
    category: "organize",
    icon: "RotateCw",
    inputLabel: "Select PDFs to rotate",
    outputLabel: "Rotated PDF",
    acceptMultiple: true,
    accept: PDF_ACCEPT,
    color: "#4F8EF7",
  },
  {
    id: "remove-pages",
    name: "Remove Pages",
    description: "Delete the pages you don't need and keep the rest of the document intact.",
    category: "organize",
    icon: "FileMinus",
    inputLabel: "Select PDF to remove pages from",
    outputLabel: "Trimmed PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
    color: "#4F8EF7",
  },
  {
    id: "reorder-pages",
    name: "Organize Pages",
    description: "Drag pages into the order you want, drop the ones you don't, and rebuild the PDF.",
    category: "organize",
    icon: "ListOrdered",
    inputLabel: "Select PDF to reorganize",
    outputLabel: "Reordered PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
    color: "#4F8EF7",
  },
  {
    id: "crop",
    name: "Crop PDF",
    description: "Trim white space or margins from every page, or only the pages you pick.",
    category: "organize",
    icon: "Crop",
    inputLabel: "Select PDF to crop",
    outputLabel: "Cropped PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
    color: "#4F8EF7",
  },
  {
    id: "add-page-numbers",
    name: "Add Page Numbers",
    description: "Stamp page numbers on every page. Pick position, style, and starting number.",
    category: "organize",
    icon: "Hash",
    inputLabel: "Select PDF to number",
    outputLabel: "Numbered PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
    color: "#4F8EF7",
  },
  {
    id: "duplicate-pages",
    name: "Copy Pages",
    description: "Repeat pages inside the same document — next to the original or appended at the end.",
    category: "organize",
    icon: "Copy",
    inputLabel: "Select PDF to copy pages from",
    outputLabel: "PDF with copied pages",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
    color: "#4F8EF7",
  },
  {
    id: "compare",
    name: "Compare PDF",
    description: "See what changed between two versions of a PDF with a line-by-line text comparison.",
    category: "organize",
    icon: "GitCompare",
    inputLabel: "Select two PDFs to compare",
    outputLabel: "Comparison report",
    acceptMultiple: true,
    accept: PDF_ACCEPT,
    color: "#4F8EF7",
  },
  // Optimize
  {
    id: "compress",
    name: "Compress PDF",
    description: "Reduce file size while keeping the best possible quality.",
    category: "optimize",
    icon: "Package",
    inputLabel: "Select PDF to compress",
    outputLabel: "Compressed PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
    color: "#F97316",
  },
  {
    id: "repair",
    name: "Repair PDF",
    description: "Rebuild a damaged or unreadable PDF and recover as much of its content as possible.",
    category: "optimize",
    icon: "Wrench",
    inputLabel: "Select damaged PDF to repair",
    outputLabel: "Repaired PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
    color: "#F97316",
  },
  {
    id: "watermark",
    name: "Watermark PDF",
    description: "Stamp text or an image over your PDFs. Choose the position and transparency.",
    category: "optimize",
    icon: "Stamp",
    inputLabel: "Select PDF to watermark",
    outputLabel: "Watermarked PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
    color: "#F97316",
  },
  // Security
  {
    id: "protect",
    name: "Protect PDF",
    description: "Encrypt a PDF with AES-256 password protection and choose what readers may do.",
    category: "security",
    icon: "Lock",
    inputLabel: "Select PDF to protect",
    outputLabel: "Protected PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
    color: "#8B5CF6",
  },
  {
    id: "unlock",
    name: "Unlock PDF",
    description: "Remove PDF password security, giving you the freedom to use your PDFs as you want.",
    category: "security",
    icon: "Unlock",
    inputLabel: "Select PDF to unlock",
    outputLabel: "Unlocked PDF",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
    color: "#8B5CF6",
  },
  // AI
  {
    id: "ai-summarize",
    name: "AI Summarizer",
    description: "Get an instant AI-generated summary and key points from any PDF. Completely free — no paywall.",
    category: "ai",
    icon: "Sparkles",
    inputLabel: "Select PDF to summarize",
    outputLabel: "Summary",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
    color: "#E5322D",
  },
  // Convert
  {
    id: "extract-text",
    name: "Extract Text",
    description: "Pull all readable text from a PDF into a .txt file, or export it as clean Markdown.",
    category: "convert",
    icon: "FileType",
    inputLabel: "Select PDF to extract text from",
    outputLabel: "Extracted Text (.txt or .md)",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
    color: "#10B981",
  },
  {
    id: "ocr",
    name: "OCR PDF",
    description: "Recognise text in scanned PDFs — including Chinese, Japanese, and Korean — as plain text, Markdown, or a searchable PDF.",
    category: "convert",
    icon: "ScanText",
    inputLabel: "Select scanned PDF to OCR",
    outputLabel: "Recognised Text (.txt or .md)",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
    color: "#10B981",
  },
  {
    id: "pdf-to-images",
    name: "PDF to JPG",
    description: "Turn each PDF page into a JPG or PNG image. Multi-page PDFs are returned as a ZIP.",
    category: "convert",
    icon: "FileImage",
    inputLabel: "Select PDF to convert to images",
    outputLabel: "Page images",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
    color: "#10B981",
  },
  {
    id: "pdf-to-pdfa",
    name: "PDF to PDF/A",
    description: "Convert a PDF into the ISO 19005 archival format for long-term storage.",
    category: "convert",
    icon: "Archive",
    inputLabel: "Select PDF to convert to PDF/A",
    outputLabel: "PDF/A document",
    acceptMultiple: false,
    accept: PDF_ACCEPT,
    color: "#10B981",
  },
  {
    id: "images-to-pdf",
    name: "Image to PDF",
    description: "Combine JPG and PNG photos into a single PDF, one image per page.",
    category: "convert",
    icon: "ImagePlus",
    inputLabel: "Select images to convert",
    outputLabel: "PDF from images",
    acceptMultiple: true,
    accept: IMAGE_ACCEPT,
    color: "#10B981",
  },
];

router.get("/tools", async (_req, res): Promise<void> => {
  res.json(PDF_TOOLS);
});

export default router;
